import { Typography } from "antd";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by Formality" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Typography.Title level={1}>
          <span className="text-[hsl(280,100%,70%)]">Test</span>
        </Typography.Title>
        <Link
          className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="/contacts"
        >
          <Typography.Title level={3}>
            <span className="text-[hsl(280,100%,70%)]">Contacts</span>
          </Typography.Title>
          Manage all contacts
        </Link>
      </main>
    </>
  );
}
